const TIMEZONES = [
  { timezone: "UTC", label: "UTC", region: "Universal" },
  { timezone: "Pacific/Midway", label: "Midway Island", region: "Pacific" },
  { timezone: "Pacific/Honolulu", label: "Honolulu", region: "Pacific" },
  { timezone: "America/Anchorage", label: "Anchorage", region: "North America" },
  { timezone: "America/Los_Angeles", label: "Los Angeles", region: "North America" },
  { timezone: "America/Vancouver", label: "Vancouver", region: "North America" },
  { timezone: "America/Denver", label: "Denver", region: "North America" },
  { timezone: "America/Phoenix", label: "Phoenix", region: "North America" },
  { timezone: "America/Chicago", label: "Chicago", region: "North America" },
  { timezone: "America/Mexico_City", label: "Mexico City", region: "North America" },
  { timezone: "America/New_York", label: "New York", region: "North America" },
  { timezone: "America/Toronto", label: "Toronto", region: "North America" },
  { timezone: "America/Miami", label: "Miami", region: "North America" },
  { timezone: "America/Halifax", label: "Halifax", region: "North America" },
  { timezone: "America/St_Johns", label: "St. John's", region: "North America" },
  { timezone: "America/Sao_Paulo", label: "São Paulo", region: "South America" },
  { timezone: "America/Buenos_Aires", label: "Buenos Aires", region: "South America" },
  { timezone: "America/Santiago", label: "Santiago", region: "South America" },
  { timezone: "America/Bogota", label: "Bogotá", region: "South America" },
  { timezone: "America/Lima", label: "Lima", region: "South America" },
  { timezone: "Atlantic/Reykjavik", label: "Reykjavik", region: "Europe" },
  { timezone: "Europe/London", label: "London", region: "Europe" },
  { timezone: "Europe/Dublin", label: "Dublin", region: "Europe" },
  { timezone: "Europe/Lisbon", label: "Lisbon", region: "Europe" },
  { timezone: "Europe/Paris", label: "Paris", region: "Europe" },
  { timezone: "Europe/Berlin", label: "Berlin", region: "Europe" },
  { timezone: "Europe/Amsterdam", label: "Amsterdam", region: "Europe" },
  { timezone: "Europe/Brussels", label: "Brussels", region: "Europe" },
  { timezone: "Europe/Madrid", label: "Madrid", region: "Europe" },
  { timezone: "Europe/Rome", label: "Rome", region: "Europe" },
  { timezone: "Europe/Zurich", label: "Zurich", region: "Europe" },
  { timezone: "Europe/Vienna", label: "Vienna", region: "Europe" },
  { timezone: "Europe/Stockholm", label: "Stockholm", region: "Europe" },
  { timezone: "Europe/Oslo", label: "Oslo", region: "Europe" },
  { timezone: "Europe/Copenhagen", label: "Copenhagen", region: "Europe" },
  { timezone: "Europe/Warsaw", label: "Warsaw", region: "Europe" },
  { timezone: "Europe/Prague", label: "Prague", region: "Europe" },
  { timezone: "Europe/Budapest", label: "Budapest", region: "Europe" },
  { timezone: "Europe/Athens", label: "Athens", region: "Europe" },
  { timezone: "Europe/Helsinki", label: "Helsinki", region: "Europe" },
  { timezone: "Europe/Bucharest", label: "Bucharest", region: "Europe" },
  { timezone: "Europe/Istanbul", label: "Istanbul", region: "Europe" },
  { timezone: "Europe/Moscow", label: "Moscow", region: "Europe" },
  { timezone: "Europe/Kiev", label: "Kyiv", region: "Europe" },
  { timezone: "Asia/Dubai", label: "Dubai", region: "Middle East" },
  { timezone: "Asia/Riyadh", label: "Riyadh", region: "Middle East" },
  { timezone: "Asia/Tehran", label: "Tehran", region: "Middle East" },
  { timezone: "Asia/Jerusalem", label: "Jerusalem", region: "Middle East" },
  { timezone: "Asia/Beirut", label: "Beirut", region: "Middle East" },
  { timezone: "Asia/Baghdad", label: "Baghdad", region: "Middle East" },
  { timezone: "Asia/Karachi", label: "Karachi", region: "Asia" },
  { timezone: "Asia/Kolkata", label: "Mumbai", region: "Asia" },
  { timezone: "Asia/Colombo", label: "Colombo", region: "Asia" },
  { timezone: "Asia/Dhaka", label: "Dhaka", region: "Asia" },
  { timezone: "Asia/Bangkok", label: "Bangkok", region: "Asia" },
  { timezone: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh", region: "Asia" },
  { timezone: "Asia/Jakarta", label: "Jakarta", region: "Asia" },
  { timezone: "Asia/Singapore", label: "Singapore", region: "Asia" },
  { timezone: "Asia/Kuala_Lumpur", label: "Kuala Lumpur", region: "Asia" },
  { timezone: "Asia/Hong_Kong", label: "Hong Kong", region: "Asia" },
  { timezone: "Asia/Shanghai", label: "Shanghai", region: "Asia" },
  { timezone: "Asia/Taipei", label: "Taipei", region: "Asia" },
  { timezone: "Asia/Manila", label: "Manila", region: "Asia" },
  { timezone: "Asia/Seoul", label: "Seoul", region: "Asia" },
  { timezone: "Asia/Tokyo", label: "Tokyo", region: "Asia" },
  { timezone: "Australia/Perth", label: "Perth", region: "Australia" },
  { timezone: "Australia/Adelaide", label: "Adelaide", region: "Australia" },
  { timezone: "Australia/Sydney", label: "Sydney", region: "Australia" },
  { timezone: "Australia/Melbourne", label: "Melbourne", region: "Australia" },
  { timezone: "Australia/Brisbane", label: "Brisbane", region: "Australia" },
  { timezone: "Pacific/Auckland", label: "Auckland", region: "Pacific" },
  { timezone: "Pacific/Fiji", label: "Fiji", region: "Pacific" },
  { timezone: "Africa/Cairo", label: "Cairo", region: "Africa" },
  { timezone: "Africa/Lagos", label: "Lagos", region: "Africa" },
  { timezone: "Africa/Nairobi", label: "Nairobi", region: "Africa" },
  { timezone: "Africa/Johannesburg", label: "Johannesburg", region: "Africa" },
  { timezone: "Africa/Casablanca", label: "Casablanca", region: "Africa" },
];
